# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8d7ac8f124b62dc1aec106536b1139719de773ee3dde51b2f5230970ee5d7e00c13985439f06bebd02700370d1ac93657884af4cd4e7661fe923bec238ad1c98

test:
  secret_key_base: bbfecf0275a84de7919f4f41a646c2cd448d818ce3b0e44711c7b3c57d6141c8551157731eff5343e17f2b156e0aa988e5e08fd1155e6e0e59ad68709969a811

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
